### ISSUE TITLE
Is this module really only compatible with Node 7?

### ISSUE THREAD

**Issue by scottmas** [teamsnap/teamsnap-javascript-sdk#208]
Hey all, my yarn package manager is yelling at me because Teamsnap says it requires Node 7, but I'm using Node 8. 

Does this module really only compatible with Node 7? Or are you looking for greater `">=7.0.0` ? In which case your package.json would have the following field: 
```
 "engines": {
    "node": ">=7.0.0",
    "npm": ">=3.0.0"
  },
```
Thanks

**Comment by matthopson** [comment]
Hey @scottmas, this is partly due to how we've been testing it on our end. I can make the change you requested, as it does make sense to lift this limitation. Thanks!

**Comment by matthopson** [comment]
@scottmas Alrighty, the update has been published to npm! :)

**Comment by scottmas** [comment]
Cool! Thanks
