### ISSUE TITLE
Lib resolution problem when running SDK on NodeJS

### ISSUE THREAD

**Issue by brolaccct** [teamsnap/teamsnap-javascript-sdk#217]
Running locally or with RunKit on NPM it appears that one of the coffee scripts is unable to resolve the xmlhttprequest dependency.

Error: Cannot find module 'xmlhttprequest' from 'request.coffee'

**Comment by jambrose42** [comment]
Confirming the same problem.  I also made sure that xmlhttprequest package is installed.

**Comment by bryanrinko** [comment]
Same....seems to be related to the override of .require that is used to load the compiled coffee is functions.  Issue shows up in the initModule as definition is undefined for xmlhttprequest.

**Comment by ryanwi** [comment]
Thank you for catching that. This library is aging a bit and based on your findings and its age, it's unlikely we'll update it to work in a node.js environment.  We're updating the docs to reflect that better.   A couple of us have built some serverless functions with the axios or request-native-promises modules which allow multiple API requests to be executed better with Promises.

Ryan Williams
TeamSnap Software Developer
