### ISSUE TITLE
teamsnap was not found in the NPM registry

### ISSUE THREAD

**Issue by ORESoftware** [teamsnap/teamsnap-javascript-sdk#30]
I tried to run:

npm install --save teamsnap

but I got these errors in my npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'teamsnap' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 warn package.json events@1.0.2 events is also the name of a node core module.
6 warn package.json node@0.0.0 No description
7 warn package.json node@0.0.0 No repository field.
8 warn package.json node@0.0.0 No README data
9 warn package.json nodejs@0.0.0 No description
10 warn package.json nodejs@0.0.0 No repository field.
11 warn package.json nodejs@0.0.0 No README data
12 warn package.json assert@1.3.0 assert is also the name of a node core module.
13 warn package.json crypto@0.0.3 crypto is also the name of a node core module.
14 warn package.json util@0.10.3 util is also the name of a node core module.
15 silly cache add args [ 'teamsnap', null ]
16 verbose cache add spec teamsnap
17 silly cache add parsed spec { raw: 'teamsnap',
17 silly cache add   scope: null,
17 silly cache add   name: 'teamsnap',
17 silly cache add   rawSpec: '',
17 silly cache add   spec: '*',
17 silly cache add   type: 'range' }
18 verbose addNamed teamsnap@*
19 silly addNamed semver.valid null
20 silly addNamed semver.validRange *
21 silly addNameRange { name: 'teamsnap', range: '*', hasData: false }
22 silly mapToRegistry name teamsnap
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry uri https://registry.npmjs.org/teamsnap
26 verbose addNameRange registry:https://registry.npmjs.org/teamsnap not in flight; fetching
27 verbose request uri https://registry.npmjs.org/teamsnap
28 verbose request no auth needed
29 info attempt registry request try #1 at 10:52:19 PM
30 verbose request id 89d603db5f306528
31 http request GET https://registry.npmjs.org/teamsnap
32 http 404 https://registry.npmjs.org/teamsnap
33 verbose headers { date: 'Tue, 07 Apr 2015 05:52:19 GMT',
33 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
33 verbose headers   'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=0',
33 verbose headers   'content-length': '51',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   age: '0',
33 verbose headers   'x-served-by': 'cache-lax1424-LAX',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1428385939.077596,VS0,VE317',
33 verbose headers   'keep-alive': 'timeout=10, max=50',
33 verbose headers   connection: 'Keep-Alive' }
34 silly get cb [ 404,
34 silly get   { date: 'Tue, 07 Apr 2015 05:52:19 GMT',
34 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
34 silly get     'content-type': 'application/json',
34 silly get     'cache-control': 'max-age=0',
34 silly get     'content-length': '51',
34 silly get     'accept-ranges': 'bytes',
34 silly get     via: '1.1 varnish',
34 silly get     age: '0',
34 silly get     'x-served-by': 'cache-lax1424-LAX',
34 silly get     'x-cache': 'MISS',
34 silly get     'x-cache-hits': '0',
34 silly get     'x-timer': 'S1428385939.077596,VS0,VE317',
34 silly get     'keep-alive': 'timeout=10, max=50',
34 silly get     connection: 'Keep-Alive' } ]
35 verbose stack Error: 404 Not Found: teamsnap
35 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:251:14)
35 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:14)
35 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
35 verbose stack     at Request.emit (events.js:110:17)
35 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
35 verbose stack     at Request.emit (events.js:129:20)
35 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
35 verbose stack     at IncomingMessage.emit (events.js:129:20)
35 verbose stack     at _stream_readable.js:908:16
35 verbose stack     at process._tickCallback (node.js:355:11)
36 verbose statusCode 404
37 verbose pkgid teamsnap
38 verbose cwd C:\Users\denman\WebstormProjects\node_sports_lineup
39 error Windows_NT 6.1.7601
40 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "teamsnap"
41 error node v0.12.1
42 error npm  v2.5.1
43 error code E404
44 error 404 Not Found: teamsnap
44 error 404
44 error 404 'teamsnap' is not in the npm registry.
44 error 404 You should bug the author to publish it (or use the name yourself!)
44 error 404 It was specified as a dependency of 'Node_Sports_Lineup'
44 error 404
44 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit [ 1, true ]

any idea what's happening?

**Comment by amberwebb** [comment]
This is still an issue. Are there any plans to publish it to the registry?

**Comment by matthopson** [comment]
It actually is in NPM - the docs were wrong... Fixed.

https://www.npmjs.com/package/teamsnap.js

Thanks!

**Comment by ORESoftware** [comment]
@matthopson 
https://www.npmjs.com/package/teamsnap.js

FYI it says both

npm install -g teamsnap

npm install -g teamsnap.js

you might want to fix it again :)

**Comment by matthopson** [comment]
@ORESoftware Are you referring to the docs on npm?

**Comment by ORESoftware** [comment]
I am referring the to the link I posted!

**Comment by matthopson** [comment]
The npm registry only updates when publishing a new module version - since it uses the repo's readme, it's still showing the old content until a new module is published - which will happen shortly. 

If you've seen the error somewhere else in the actual github repo feel free to let me know, otherwise the npm page will update automatically soon. 

Thanks

**Comment by ORESoftware** [comment]
for sure just trying to keep the world sane
