### ISSUE TITLE
request is defined twice

### ISSUE THREAD

**Issue by ORESoftware** [teamsnap/teamsnap-javascript-sdk#31]
was looking through the code (looks good), but one minor issue is that request is defined twice in teamsnap.js

request = require('./request');

promises = require('./promises');

request = require('./request');

(you'll see it)

**Comment by falonofthetower** [comment]
Possibly resolved with this https://github.com/teamsnap/teamsnap-javascript-sdk/pull/57

Sorry about the multiple attempts was trying to properly format the commit from the command line.
