### ISSUE TITLE
Error on bulk load call 

### ISSUE THREAD

**Issue by lchilson** [teamsnap/teamsnap-javascript-sdk#94]
"The following 'types' are invalid: broadcast_sms"

**Comment by lchilson** [comment]
Cannot read prop type links either now

**Comment by dmccraw** [comment]
`broadcast_sms` is no longer a valid type. It has been converted to `broadcast_alert`

**Comment by knappe** [comment]
@lchilson Do you need further help with the SDK or are we okay to close this?

**Comment by knappe** [comment]
Confirmed with @matthopson That this issue is good to close.  Thanks for using the sdk @lchilson!
